import random

FUNDS = [
    {
        "name": "Motilal Oswal Large Cap Fund",
        "amc": "Motilal Oswal",
        "category": "Large Cap",
        "risk": "Moderate",
        "expense_ratio": 0.35,
        "aum_cr": 28500,
        "cagr_3y": 13.2,
        "cagr_5y": 15.1,
        "min_sip": 1000,
        "rating": 5,
        "insight": "Consistent outperformer with disciplined value-oriented investing and experienced management."
    },
    {
        "name": "ICICI Prudential Bluechip Fund",
        "amc": "ICICI Prudential",
        "category": "Large Cap",
        "risk": "Moderate",
        "expense_ratio": 0.42,
        "aum_cr": 42100,
        "cagr_3y": 11.8,
        "cagr_5y": 13.5,
        "min_sip": 1000,
        "rating": 5,
        "insight": "Stable large-cap fund with strong track record and robust risk management."
    },
    {
        "name": "HDFC Top 100 Fund",
        "amc": "HDFC",
        "category": "Large Cap",
        "risk": "Moderate",
        "expense_ratio": 0.38,
        "aum_cr": 31500,
        "cagr_3y": 12.5,
        "cagr_5y": 14.0,
        "min_sip": 500,
        "rating": 5,
        "insight": "Classic large-cap fund with focus on quality and sustainable growth."
    },
    {
        "name": "SBI Bluechip Fund",
        "amc": "SBI",
        "category": "Large Cap",
        "risk": "Moderate",
        "expense_ratio": 0.40,
        "aum_cr": 36800,
        "cagr_3y": 11.5,
        "cagr_5y": 13.0,
        "min_sip": 500,
        "rating": 4,
        "insight": "Reliable bluechip fund with steady returns and low volatility."
    },
    {
        "name": "Nippon India Large Cap Fund",
        "amc": "Nippon India",
        "category": "Large Cap",
        "risk": "Moderate",
        "expense_ratio": 0.45,
        "aum_cr": 19200,
        "cagr_3y": 12.0,
        "cagr_5y": 13.8,
        "min_sip": 1000,
        "rating": 4,
        "insight": "Aggressive large-cap fund with strong momentum-based strategies."
    },
    {
        "name": "Motilal Oswal Midcap Fund",
        "amc": "Motilal Oswal",
        "category": "Mid Cap",
        "risk": "High",
        "expense_ratio": 0.55,
        "aum_cr": 18500,
        "cagr_3y": 18.5,
        "cagr_5y": 22.3,
        "min_sip": 1000,
        "rating": 5,
        "insight": "High-growth mid-cap fund with proven stock selection ability."
    },
    {
        "name": "HDFC Midcap Opportunities Fund",
        "amc": "HDFC",
        "category": "Mid Cap",
        "risk": "High",
        "expense_ratio": 0.52,
        "aum_cr": 41200,
        "cagr_3y": 16.2,
        "cagr_5y": 19.8,
        "min_sip": 500,
        "rating": 5,
        "insight": "Diversified mid-cap fund with strong research-backed portfolio construction."
    },
    {
        "name": "Nippon India Growth Fund",
        "amc": "Nippon India",
        "category": "Mid Cap",
        "risk": "High",
        "expense_ratio": 0.58,
        "aum_cr": 22100,
        "cagr_3y": 17.1,
        "cagr_5y": 20.5,
        "min_sip": 1000,
        "rating": 4,
        "insight": "Growth-oriented mid-cap fund with focus on emerging leaders."
    },
    {
        "name": "Kotak Emerging Equity Fund",
        "amc": "Kotak",
        "category": "Mid Cap",
        "risk": "High",
        "expense_ratio": 0.50,
        "aum_cr": 17800,
        "cagr_3y": 15.8,
        "cagr_5y": 18.9,
        "min_sip": 1000,
        "rating": 4,
        "insight": "Quality mid-cap fund with disciplined rebalancing and risk control."
    },
    {
        "name": "Parag Parikh Flexi Cap Fund",
        "amc": "Parag Parikh",
        "category": "Flexi Cap",
        "risk": "Moderate",
        "expense_ratio": 0.45,
        "aum_cr": 55000,
        "cagr_3y": 16.8,
        "cagr_5y": 19.5,
        "min_sip": 1000,
        "rating": 5,
        "insight": "Internationally diversified flexi-cap fund with a value-investing approach."
    },
    {
        "name": "ICICI Prudential Flexi Cap Fund",
        "amc": "ICICI Prudential",
        "category": "Flexi Cap",
        "risk": "Moderate",
        "expense_ratio": 0.48,
        "aum_cr": 28500,
        "cagr_3y": 14.5,
        "cagr_5y": 16.2,
        "min_sip": 1000,
        "rating": 5,
        "insight": "Dynamic allocation across market caps with strong risk-adjusted returns."
    },
    {
        "name": "Kotak Flexi Cap Fund",
        "amc": "Kotak",
        "category": "Flexi Cap",
        "risk": "Moderate",
        "expense_ratio": 0.42,
        "aum_cr": 19500,
        "cagr_3y": 13.9,
        "cagr_5y": 15.8,
        "min_sip": 1000,
        "rating": 4,
        "insight": "Flexible portfolio with focus on business quality and valuation discipline."
    },
    {
        "name": "SBI Flexi Cap Fund",
        "amc": "SBI",
        "category": "Flexi Cap",
        "risk": "Moderate",
        "expense_ratio": 0.44,
        "aum_cr": 16800,
        "cagr_3y": 14.1,
        "cagr_5y": 16.0,
        "min_sip": 500,
        "rating": 4,
        "insight": "Balanced flexi-cap fund with consistent performance across market cycles."
    },
    {
        "name": "Nippon India Small Cap Fund",
        "amc": "Nippon India",
        "category": "Small Cap",
        "risk": "Very High",
        "expense_ratio": 0.65,
        "aum_cr": 14500,
        "cagr_3y": 22.4,
        "cagr_5y": 25.1,
        "min_sip": 1000,
        "rating": 4,
        "insight": "High-conviction small-cap fund with aggressive growth focus."
    },
    {
        "name": "Axis Small Cap Fund",
        "amc": "Axis",
        "category": "Small Cap",
        "risk": "Very High",
        "expense_ratio": 0.60,
        "aum_cr": 21000,
        "cagr_3y": 21.0,
        "cagr_5y": 24.0,
        "min_sip": 500,
        "rating": 5,
        "insight": "Quality small-cap fund with strong portfolio concentration in winners."
    },
    {
        "name": "SBI Small Cap Fund",
        "amc": "SBI",
        "category": "Small Cap",
        "risk": "Very High",
        "expense_ratio": 0.58,
        "aum_cr": 12500,
        "cagr_3y": 20.5,
        "cagr_5y": 23.5,
        "min_sip": 500,
        "rating": 4,
        "insight": "Disciplined small-cap fund with focus on niche market leaders."
    },
    {
        "name": "HDFC TaxSaver (ELSS) Fund",
        "amc": "HDFC",
        "category": "ELSS",
        "risk": "High",
        "expense_ratio": 0.50,
        "aum_cr": 23500,
        "cagr_3y": 14.8,
        "cagr_5y": 16.5,
        "min_sip": 500,
        "rating": 5,
        "insight": "Tax-saving fund with multi-cap exposure and strong long-term track record."
    },
    {
        "name": "Mirae Asset TaxSaver Fund",
        "amc": "Mirae",
        "category": "ELSS",
        "risk": "High",
        "expense_ratio": 0.45,
        "aum_cr": 19800,
        "cagr_3y": 15.2,
        "cagr_5y": 17.0,
        "min_sip": 500,
        "rating": 5,
        "insight": "Dynamic ELSS fund with focus on growth-oriented large and mid caps."
    },
    {
        "name": "ICICI Prudential Long Term Equity Fund",
        "amc": "ICICI Prudential",
        "category": "ELSS",
        "risk": "High",
        "expense_ratio": 0.48,
        "aum_cr": 16500,
        "cagr_3y": 13.9,
        "cagr_5y": 15.8,
        "min_sip": 1000,
        "rating": 4,
        "insight": "Balanced ELSS fund with consistent performance and downside protection."
    },
    {
        "name": "SBI Liquid Fund",
        "amc": "SBI",
        "category": "Liquid Fund",
        "risk": "Low",
        "expense_ratio": 0.20,
        "aum_cr": 42000,
        "cagr_3y": 5.2,
        "cagr_5y": 5.5,
        "min_sip": 1000,
        "rating": 5,
        "insight": "Top-rated liquid fund with excellent liquidity and stable returns."
    },
    {
        "name": "HDFC Liquid Fund",
        "amc": "HDFC",
        "category": "Liquid Fund",
        "risk": "Low",
        "expense_ratio": 0.22,
        "aum_cr": 38500,
        "cagr_3y": 5.1,
        "cagr_5y": 5.4,
        "min_sip": 500,
        "rating": 5,
        "insight": "High-quality liquid fund with low volatility and consistent performance."
    },
    {
        "name": "ICICI Prudential Liquid Fund",
        "amc": "ICICI Prudential",
        "category": "Liquid Fund",
        "risk": "Low",
        "expense_ratio": 0.21,
        "aum_cr": 35200,
        "cagr_3y": 5.0,
        "cagr_5y": 5.3,
        "min_sip": 1000,
        "rating": 5,
        "insight": "Low-volatility liquid fund ideal for short-term parking of funds."
    },
    {
        "name": "SBI Short Term Debt Fund",
        "amc": "SBI",
        "category": "Debt Fund",
        "risk": "Low",
        "expense_ratio": 0.30,
        "aum_cr": 21500,
        "cagr_3y": 6.5,
        "cagr_5y": 7.0,
        "min_sip": 500,
        "rating": 5,
        "insight": "Low-duration debt fund with stable returns and minimal interest rate risk."
    },
    {
        "name": "HDFC Short Term Debt Fund",
        "amc": "HDFC",
        "category": "Debt Fund",
        "risk": "Low",
        "expense_ratio": 0.32,
        "aum_cr": 18800,
        "cagr_3y": 6.3,
        "cagr_5y": 6.8,
        "min_sip": 500,
        "rating": 4,
        "insight": "Quality debt fund with focus on high-quality instruments and accrual strategy."
    },
    {
        "name": "ICICI Prudential Short Term Fund",
        "amc": "ICICI Prudential",
        "category": "Debt Fund",
        "risk": "Low",
        "expense_ratio": 0.28,
        "aum_cr": 16200,
        "cagr_3y": 6.4,
        "cagr_5y": 6.9,
        "min_sip": 1000,
        "rating": 4,
        "insight": "Conservative debt fund with high credit quality and predictable returns."
    },
    {
        "name": "SBI Hybrid Equity Fund",
        "amc": "SBI",
        "category": "Hybrid Fund",
        "risk": "Moderate",
        "expense_ratio": 0.55,
        "aum_cr": 24500,
        "cagr_3y": 12.0,
        "cagr_5y": 13.5,
        "min_sip": 500,
        "rating": 5,
        "insight": "Aggressive hybrid fund with dynamic equity-debt allocation for risk-adjusted returns."
    },
    {
        "name": "HDFC Hybrid Equity Fund",
        "amc": "HDFC",
        "category": "Hybrid Fund",
        "risk": "Moderate",
        "expense_ratio": 0.52,
        "aum_cr": 19800,
        "cagr_3y": 11.5,
        "cagr_5y": 13.0,
        "min_sip": 1000,
        "rating": 4,
        "insight": "Balanced hybrid fund with equity bias and debt cushioning."
    },
    {
        "name": "ICICI Prudential Balanced Advantage Fund",
        "amc": "ICICI Prudential",
        "category": "Hybrid Fund",
        "risk": "Moderate",
        "expense_ratio": 0.58,
        "aum_cr": 36500,
        "cagr_3y": 11.0,
        "cagr_5y": 12.5,
        "min_sip": 1000,
        "rating": 5,
        "insight": "Dynamic asset allocation fund with built-in volatility management."
    },
    {
        "name": "Nippon India Golden Peacock Fund",
        "amc": "Nippon India",
        "category": "Gold ETF",
        "risk": "Moderate",
        "expense_ratio": 0.25,
        "aum_cr": 8500,
        "cagr_3y": 10.5,
        "cagr_5y": 12.0,
        "min_sip": 500,
        "rating": 4,
        "insight": "Gold ETF providing inflation hedge and portfolio diversification."
    },
    {
        "name": "HDFC Gold ETF",
        "amc": "HDFC",
        "category": "Gold ETF",
        "risk": "Moderate",
        "expense_ratio": 0.22,
        "aum_cr": 6200,
        "cagr_3y": 10.2,
        "cagr_5y": 11.8,
        "min_sip": 500,
        "rating": 4,
        "insight": "Low-cost gold ETF for portfolio hedging and safe-haven exposure."
    },
    {
        "name": "SBI Gold ETF",
        "amc": "SBI",
        "category": "Gold ETF",
        "risk": "Moderate",
        "expense_ratio": 0.20,
        "aum_cr": 4800,
        "cagr_3y": 10.0,
        "cagr_5y": 11.5,
        "min_sip": 500,
        "rating": 4,
        "insight": "Tracks domestic gold prices with high liquidity and low tracking error."
    },
    {
        "name": "Mirae Asset Multi Cap Fund",
        "amc": "Mirae",
        "category": "Multi Cap",
        "risk": "High",
        "expense_ratio": 0.50,
        "aum_cr": 28000,
        "cagr_3y": 15.5,
        "cagr_5y": 18.0,
        "min_sip": 1000,
        "rating": 5,
        "insight": "Multi-cap fund with flexible market-cap weighting and strong research edge."
    },
    {
        "name": "Kotak Multi Cap Fund",
        "amc": "Kotak",
        "category": "Multi Cap",
        "risk": "High",
        "expense_ratio": 0.48,
        "aum_cr": 16500,
        "cagr_3y": 14.8,
        "cagr_5y": 17.2,
        "min_sip": 1000,
        "rating": 4,
        "insight": "Diversified multi-cap fund with focus on high-conviction ideas."
    },
    {
        "name": "Axis Multi Cap Fund",
        "amc": "Axis",
        "category": "Multi Cap",
        "risk": "High",
        "expense_ratio": 0.52,
        "aum_cr": 14200,
        "cagr_3y": 14.5,
        "cagr_5y": 16.8,
        "min_sip": 1000,
        "rating": 4,
        "insight": "Growth-oriented multi-cap fund with emphasis on quality and scale."
    },
]


def get_funds_by_category(category: str):
    return [f for f in FUNDS if f["category"] == category]


def get_random_funds(category: str, count: int = 3):
    funds = get_funds_by_category(category)
    if len(funds) <= count:
        return funds
    return random.sample(funds, count)
